blank_issues_enabled: false
contact_links:
  - name: NetBox upstream
    url: https://github.com/netbox-community/netbox/issues
    about: Report bugs or feature requests for NetBox itself (not this plugin).
