# Generated by Django 6.1 on 2026-09-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peeringnetworkpeeringdb',
            name='ixlan_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
