# Generated by Django 4.2.4 on 2023-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0067_ipaddress_index_host'),
        ('tenancy', '0011_contactassignment_tags'),
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
        ('dcim', '0181_rename_device_role_device_role'),
        ('netbox_peering_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='BGPCommunity',
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
