# Generated by Django 4.2.4 on 2023-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0064_clear_search_cache"),
        ("tenancy", "0009_standardize_description_comments"),
        ("extras", "0084_staging"),
        ("dcim", "0167_module_status"),
        ('netbox_peering_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='BGPCommunity',
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
