# Generated by Django 4.2.4 on 2023-09-25 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0011_contactassignment_tags"),
        ("ipam", "0064_clear_search_cache"),
        ("netbox_peering_manager", "0002_rename_community_bgpcommunity_alter_bgpsession_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bgpcommunity",
            name="value",
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator("\\d+:\\d+L?")]),
        ),
        migrations.AlterUniqueTogether(
            name="bgpcommunity",
            unique_together={("value", "tenant")},
        ),
    ]
