# Generated by Django 4.2.4 on 2023-09-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0003_bgpcommunity_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bgpcommunity',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunity',
            constraint=models.UniqueConstraint(fields=('value', 'tenant', 'site'), name='unique_value_tenant_site'),
        ),
    ]
