# Generated by Django 4.2.4 on 2023-09-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0004_alter_bgpcommunity_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bgpcommunity',
            name='unique_value_tenant_site',
        ),
        migrations.AddConstraint(
            model_name='bgpcommunity',
            constraint=models.UniqueConstraint(fields=('value', 'tenant', 'site'), name='netbox_peering_manager_bgpcommunity_value_tenant_site_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunity',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('value', 'site'), name='netbox_peering_manager_bgpcommunity_value_site_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunity',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('value', 'tenant'), name='netbox_peering_manager_bgpcommunity_value_tenant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunity',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('site__isnull', True)), fields=('value',), name='netbox_peering_manager_bgpcommunity__value_uniq'),
        ),
    ]
