# Generated by Django 3.2 on 2021-04-28 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_peering_manager", "0013_netbox_peering_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asngroup",
            name="slug",
        ),
    ]
