# Generated by Django 5.2.7 on 2025-10-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0035_alter_aspathlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspathlistrule',
            options={'ordering': ['aspath_list', 'index']},
        ),
    ]
