# Generated by Claude for netbox-peering-manager

import django.core.validators
import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
        ('netbox_peering_manager', '0036_alter_aspathlistrule_options'),
    ]

    operations = [
        # Create Relationship model
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='9e9e9e', max_length=6)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'ordering': ['name'],
            },
        ),
        # Create BFD model
        migrations.CreateModel(
            name='BFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('minimum_transmit_interval', models.PositiveIntegerField(
                    default=300,
                    help_text='Minimum transmit interval in milliseconds',
                    validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(60000)],
                )),
                ('minimum_receive_interval', models.PositiveIntegerField(
                    default=300,
                    help_text='Minimum receive interval in milliseconds',
                    validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(60000)],
                )),
                ('detect_multiplier', models.PositiveSmallIntegerField(
                    default=3,
                    help_text='Detection time multiplier',
                    validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)],
                )),
                ('hold_time', models.PositiveIntegerField(
                    blank=True,
                    help_text='Optional hold time override in milliseconds',
                    null=True,
                )),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BFD Profile',
                'verbose_name_plural': 'BFD Profiles',
                'ordering': ['name'],
            },
        ),
        # Add new fields to BGPSession
        migrations.AddField(
            model_name='bgpsession',
            name='relationship',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sessions',
                to='netbox_peering_manager.relationship',
            ),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='bfd',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sessions',
                to='netbox_peering_manager.bfd',
            ),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='multihop_ttl',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='TTL for eBGP multihop (1 = directly connected)',
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)],
            ),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='service_reference',
            field=models.CharField(
                blank=True,
                help_text='External service reference (e.g., circuit ID, order number)',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='enabled',
            field=models.BooleanField(
                default=True,
                help_text='Administrative enable/disable of this session',
            ),
        ),
    ]
