# Generated by Django 5.2.8 on 2025-11-28 20:10

import django.core.validators
import utilities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0037_relationship_bfd_bgpsession_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfd',
            name='hold_time',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='color',
            field=utilities.fields.ColorField(default='9e9e9e', max_length=6),
        ),
    ]
