# Generated by Django 5.2.8 on 2026-01-06 05:01

import django.db.models.deletion
import utilities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0040_irr_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peeringfabric',
            name='peeringdb_id',
        ),
        migrations.AlterField(
            model_name='peeringfabrictype',
            name='color',
            field=utilities.fields.ColorField(default='9e9e9e', max_length=6),
        ),
        migrations.CreateModel(
            name='PeeringFabricPeeringDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ix_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('website', models.URLField(blank=True)),
                ('tech_email', models.EmailField(blank=True, max_length=254)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peeringdb', to='netbox_peering_manager.peeringfabric')),
            ],
            options={
                'verbose_name': 'PeeringDB Info',
                'verbose_name_plural': 'PeeringDB Info',
            },
        ),
        migrations.CreateModel(
            name='PeeringNetworkPeeringDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ixlan_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mtu', models.PositiveIntegerField(blank=True, null=True)),
                ('rs_asn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dot1q_support', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peeringdb', to='netbox_peering_manager.peeringnetwork')),
            ],
            options={
                'verbose_name': 'PeeringDB IXLAN Info',
                'verbose_name_plural': 'PeeringDB IXLAN Info',
            },
        ),
        migrations.CreateModel(
            name='PeeringDBPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('asn', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ipv4_addr', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_addr', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('is_rs_peer', models.BooleanField(default=False)),
                ('speed', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peeringdb_peers', to='netbox_peering_manager.peeringfabric')),
            ],
            options={
                'verbose_name': 'PeeringDB Peer',
                'verbose_name_plural': 'PeeringDB Peers',
                'ordering': ['asn', 'name'],
                'unique_together': {('fabric', 'asn', 'ipv4_addr', 'ipv6_addr')},
            },
        ),
    ]
