# Generated by Django 5.2.8 on 2026-01-07 02:18

import netbox_peering_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0041_remove_peeringfabric_peeringdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='value',
            field=models.CharField(max_length=64, validators=[netbox_peering_manager.validators.validate_community]),
        ),
    ]
