# Generated by Django 5.2.8 on 2026-01-07 02:47

from django.db import migrations, models


def convert_family_to_integer(apps, schema_editor):
    """Convert string family values to integers."""
    PrefixList = apps.get_model('netbox_peering_manager', 'PrefixList')
    mapping = {'ipv4': 4, 'ipv6': 6}
    for prefix_list in PrefixList.objects.all():
        if prefix_list.family in mapping:
            prefix_list.family = mapping[prefix_list.family]
            prefix_list.save(update_fields=['family'])


def convert_family_to_string(apps, schema_editor):
    """Reverse: convert integer family values to strings."""
    PrefixList = apps.get_model('netbox_peering_manager', 'PrefixList')
    mapping = {4: 'ipv4', 6: 'ipv6'}
    for prefix_list in PrefixList.objects.all():
        if prefix_list.family in mapping:
            prefix_list.family = mapping[prefix_list.family]
            prefix_list.save(update_fields=['family'])


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0042_alter_community_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routingpolicy',
            options={'ordering': ['-weight', 'name']},
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='address_family',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(convert_family_to_integer, convert_family_to_string),
        migrations.AlterField(
            model_name='prefixlist',
            name='family',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
