# Generated by Django 5.2.8 on 2026-01-07 19:22

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('ipam', '0083_vlangroup_populate_total_vlan_ids'),
        ('netbox_peering_manager', '0043_phase4_security_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('affiliated', models.BooleanField(default=False)),
                ('irr_as_set', models.CharField(blank=True, max_length=100)),
                ('ipv4_max_prefixes', models.PositiveIntegerField(blank=True, null=True)),
                ('ipv6_max_prefixes', models.PositiveIntegerField(blank=True, null=True)),
                ('peeringdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('peeringdb_last_sync', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('asn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_asn', to='ipam.asn')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Peer ASN',
                'verbose_name_plural': 'Peer ASNs',
                'ordering': ['asn__asn'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
