# Generated by Django 5.2.8 on 2026-01-07 19:34

import django.db.models.deletion
from django.db import migrations, models


def create_peer_asns_for_sessions(apps, schema_editor):
    """Create PeerASN records and update BGPSession references."""
    BGPSession = apps.get_model("netbox_peering_manager", "BGPSession")
    PeerASN = apps.get_model("netbox_peering_manager", "PeerASN")

    # Get unique ASN IDs used as remote_as
    asn_ids = BGPSession.objects.values_list("remote_as_id", flat=True).distinct()

    # Create PeerASN for each unique ASN and build mapping
    asn_to_peerasn = {}
    for asn_id in asn_ids:
        if asn_id:
            peer_asn, created = PeerASN.objects.get_or_create(asn_id=asn_id)
            asn_to_peerasn[asn_id] = peer_asn.pk

    # Update BGPSession references to point to PeerASN IDs
    for asn_id, peer_asn_id in asn_to_peerasn.items():
        BGPSession.objects.filter(remote_as_id=asn_id).update(remote_as_id=peer_asn_id)


def reverse_migration(apps, schema_editor):
    """No-op for reverse - keep PeerASN records."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0044_create_peerasn'),
    ]

    operations = [
        # First create PeerASN for each existing remote_as
        migrations.RunPython(create_peer_asns_for_sessions, reverse_migration),

        # Then alter the field
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_as',
            field=models.ForeignKey(
                help_text="Peer ASN for this session",
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sessions',
                to='netbox_peering_manager.peerasn',
            ),
        ),
    ]
