# Generated by Django 5.2.8 on 2026-01-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0045_update_bgpsession_remote_as'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bgpsession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='peeringfabric',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'local_address', 'local_as', 'remote_address', 'remote_as'), name='unique_bgpsession_device'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('virtualmachine__isnull', False)), fields=('virtualmachine', 'local_address', 'local_as', 'remote_address', 'remote_as'), name='unique_bgpsession_vm'),
        ),
        migrations.AddConstraint(
            model_name='peeringfabric',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('name', 'site'), name='unique_peeringfabric_name_site'),
        ),
        migrations.AddConstraint(
            model_name='peeringfabric',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('name',), name='unique_peeringfabric_name_no_site'),
        ),
    ]
