# Generated by Django 5.2.8 on 2026-01-08 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_peering_manager', '0046_unique_constraints_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='virtualmachine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualization.virtualmachine'),
        ),
    ]
