# Generated by Django 5.2.2 on 2025-06-21 20:43

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0033_alter_bgpsession_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASPathList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'AS Path Lists',
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.AddField(
            model_name='routingpolicyrule',
            name='match_aspath_list',
            field=models.ManyToManyField(blank=True, related_name='aspathrules', to='netbox_bgp.aspathlist'),
        ),
        migrations.CreateModel(
            name='ASPathListRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('index', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('pattern', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('aspath_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspathlistrules', to='netbox_bgp.aspathlist')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
